(define (make-segment a b)
  (cons a b))
(define (start-segment seg)
  (car seg))
(define (end-segment seg)
  (cdr seg))
(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))

(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (midpoint-segment seg)
  (make-point (average (x-point (start-segment seg))
		       (x-point (end-segment seg)))
	      (average (y-point (start-segment seg))
		       (y-point (end-segment seg)))))

(define (make-rectangle top-left-point width height)
  (cons top-left-point (cons width height)))
(define (rect-width r)
  (car (cdr r)))
(define (rect-height r)
  (cdr (cdr r)))

(define (rect-perimeter r)
  (* (+ (rect-width r) (rect-height r)) 2))
(define (rect-area r)
  (* (rect-width r) (rect-height r)))

(define myrect (make-rectangle (make-point 2 2) 4 2))
(rect-area myrect)
(rect-perimeter myrect)

